name: "Deploy and Destroy Workflows"

on:
  schedule:
    - cron: '0 1 * * 6'
    - cron: '30 3 * * 6'
    - cron: '0 5 * * 6'
    - cron: '30 7 * * 6'

jobs:
  usecase_schedule:
    name: "Trigger Actions Schedules"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Deploy workflow
        run: gh workflow run waf-on-ce-aws-apply.yml --ref deploy-waf-aws-ce
        if: github.event.schedule == '0 1 * * 6'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      - name: Trigger Destroy workflow
        run: gh workflow run waf-on-ce-aws-destroy.yml --ref destroy-waf-aws-ce
        if: github.event.schedule == '30 3 * * 6'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Deploy workflow
        run: gh workflow run waf-re-apply.yml --ref deploy-waf-re
        if: github.event.schedule == '0 5 * * 6'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Destroy workflow
        run: gh workflow run waf-re-destroy.yml --ref destroy-waf-re
        if: github.event.schedule == '30 7 * * 6'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
     - name: Trigger Deploy workflow
        run: gh workflow run waf-re-ac-az-apply.yml --ref deploy-waf-re-ac-vm
        if: github.event.schedule == '0 5 * * 6'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger Destroy workflow
        run: gh workflow run waf-re-ac-az-destroy.yml --ref destroy-waf-re-ac-vm
        if: github.event.schedule == '30 7 * * 6'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     - name: Trigger Deploy workflow
        run: gh workflow run waf-k8s-apply.yml --ref deploy-waf-k8s
        if: github.event.schedule == '0 5 * * 6'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Destroy workflow
        run: gh workflow run waf-k8s-destroy.yml --ref destroy-waf-k8s
        if: github.event.schedule == '30 7 * * 6'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
