name: "Deploy and Destroy Workflows"

on:
  schedule:
    - cron: '30 1 * * 3'
    - cron: '0 3 * * 3'
    - cron: '30 12 * * 0'
    - cron: '30 14 * * 0'

jobs:
  usecase_schedule:
    name: "Trigger Actions Schedules"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Deploy workflow
        run: gh workflow run waf-on-ce-aws-apply.yaml --ref deploy-waf-aws-ce
        if: github.event.schedule == '30 1 * * 3'
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_SECRET }}   

      - name: Trigger Destroy workflow
        run: gh workflow run waf-on-ce-aws-destroy.yaml --ref destroy-waf-aws-ce
        if: github.event.schedule == '0 3 * * 3'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Trigger Deploy workflow
      #   run: gh workflow run waf-on-ce-aws-apply.yml --ref deploy-waf-aws-ce
      #   if: github.event.schedule == '30 128 * * 0'
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Trigger Destroy workflow
      #   run: gh workflow run waf-on-ce-aws-destroy.yml --ref destroy-waf-aws-ce
      #   if: github.event.schedule == '30 148 * * 0'
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}