name: "Deploy and Destroy Workflows"

on:
  schedule:
    - cron: '0 2 * * 2'
    - cron: '0 3 * * 2'
    - cron: '0 4 * * 2'
    - cron: '0 5 * * 2'
    - cron: '0 6 * * 2'
    - cron: '0 7 * * 2'

jobs:
  usecase_schedule:
    name: "Trigger Actions Schedules"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Deploy workflow
        run: gh workflow run waf-re-apply.yml --ref deploy-waf-re
        if: github.event.schedule == '0 2 * * 2'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Destroy workflow
        run: gh workflow run waf-re-destroy.yml --ref destroy-waf-re
        if: github.event.schedule == '0 3 * * 2'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Deploy workflow
        run: gh workflow run waf-on-ce-aws-apply.yml --ref deploy-waf-aws-ce
        if: github.event.schedule == '0 4 * * 2'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      - name: Trigger Destroy workflow
        run: gh workflow run waf-on-ce-aws-destroy.yml --ref destroy-waf-aws-ce
        if: github.event.schedule == '0 5 * * 2'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Deploy workflow
        run: gh workflow run waf-k8s-apply.yml --ref deploy-waf-k8s
        if: github.event.schedule == '0 6 * * 2'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      - name: Trigger Destroy workflow
        run: gh workflow run waf-k8s-destroy.yml --ref destroy-waf-k8s
        if: github.event.schedule == '0 7 * * 2'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
